;
; LAB5.asm
;
; Created: 23/09/2020 07:30:35 a. m.
; Author : Roberto Duarte
;


; Replace with your application code
.ORG 0
.INCLUDE "m16def.inc"
.DEF LED=R25

;STACK PILE
LDI R16,HIGH(RAMEND)
OUT SPH,R16
LDI R16,LOW(RAMEND)
OUT SPL,R16


SER R16; PONER EL REGISTRO A 1
OUT DDRC,R16; CONFIGURAR EL PUERTO C COMO SALIDA (LEDS)
SER R16; PONER EL REGISTRO A 1
OUT DDRB,R16; CONFIGURAR EL PUERTO B COMO SALIDA (7SEGMENTOS)


LDI R24,8; GUARDAR UN 8 EN EL REGISTRO R24
LDI R17,255; GUARDAR 255 EN REGISTRO R17




REGRESAR:
SBIC PINA,0; SI EL BIT 0 DEL PINA ESTA EN CERO, SE SALTA LA SIGUIENTE INSTRUCCION
CALL SW1; SI EL BIT 0 DEL PINA NO ES CERO, SE EJECUTA ESTA INSTRUCCION, LA CUAL LLAMA A UN SUBPROCESO(CONTEO DESCENDENTE)

SBIC PINA,1
CALL SW2;(ROTACION DE LEDS)

SBIC PINA,2
CALL SW3;(CONTADOR ASCENDENTE BCD)

RJMP REGRESAR; EN CASO DE QUE TODOS LOS 3 PRIMEROS BITS DEL PINA ESTEN EN 0, SE VUELVE A INICIAR EL PROCESO DESDE LA ETIQUETA REGRESAR

SW1:
CONTEO1:
OUT PORTC,R17; SE DESPLIEGA EN EL PUERTO C EL VALOR GUARDADO EN R17(INICIALMENTE 255)
DEC R17; EL VALOR GUARDADO EN R17 SE DECREMENTA EN UNA UNIDAD
CALL delay100ms; DELAY DE 100ms
BRNE CONTEO1; MIENTRAS EL VALOR GUARDADO EN R17 NO SEA 0, O Z=0, SE REPETIRA EL PROCESO A PARTIR DE LA ETIQUETA CONTEO1
RET; REGRESA A LA INSTRUCCION SIGUIENTE DE DONDE SE LLAMO AL PROCESO SW1


SW2:
CLR LED; PONE EL REGISTRO EN CEROS
CALL delay100ms
CALL delay100ms
;CPI R24,8
;BRSH DER
;BRLO IZQ
CALL DER; LLAMA AL SUBPROCESO NECESARIO PARA GIRAR A LA DERECHA, CUANDO TERMINE ESTE SUBPROCESO SE REGRESARA AL SIGUIENTE INSTRUCCION
CALL IZQ
RET; REGRESA AL MONITOREO DEL ESTADO DE LOS SWITCHES

DER: 
LDI R24,8
GIRODER:
CALL delay100ms
CALL delay100ms
SEC 
ROR LED
OUT PORTC,LED
DEC R24
BRNE GIRODER
RET

IZQ:
LDI R24,8
GIROIZQ:
CALL delay100ms
CALL delay100ms
CLC
ROL LED
OUT PORTC,LED
DEC R24
BRNE GIROIZQ
RET

SW3:
LDI R18,0; 
CONTEO3:
OUT PORTB,R18;
INC R18
CALL delay100ms
CALL delay100ms
CALL delay100ms
CALL delay100ms
CALL delay100ms
CPI R18,10
BRNE CONTEO3
RET



delay10ms:	LDI R21, 104
	loop1:	LDI R22 ,255 
	loop2:	DEC R22 
			BRNE loop2
			DEC R21
			BRNE loop1
RET 

delay100ms:
		LDI R23, 10
loop3:	CALL delay10ms
		DEC R23
		BRNE loop3
RET